language: java
dist: trusty
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
before_script:
- "./gradlew test"
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: f1f60895-8958-4b7e-bb14-c2b596601def
  app: group2-ita06-ezticket-backend
  on:
    repo: Group-2-ezTicket/ezTicket-backend
