INSERT INTO CINEMA (NAME) VALUES ('SM South Mall - Cinema 1');
INSERT INTO CINEMA (NAME) VALUES ('SM South Mall - Cinema 2');
INSERT INTO CINEMA (NAME) VALUES ('SM North Edsa - Cinema 1');
INSERT INTO CINEMA (NAME) VALUES ('SM North Edsa - Cinema 2');

INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('Black Widow', 'Black Widow destroys the red room c:',4,3,'Action',300);
INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('Luca','Sample Synopsis.',7.5,2,'Cartoon',250);
INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('The Spongebob Squarepants Movie','Sample Synopsis.',5,2,'Cartoon',200);
INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('Venom','Sample Synopsis.',6,2.5,'Action',250);
INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('Free Guy','Sample Synopsis.',7.5,2,'Cartoon',250);
INSERT INTO MOVIES  (MOVIETITLE,SYNOPSIS,RATING,DURATION,GENRE,PRICE) VALUES ('Regular Show The Movie','Sample Synopsis.',7.5,2,'Cartoon',250);

INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (1,'9:00:00','11:30:00','2021-08-24',1);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (1,'12:00:00','2:30:00','2021-08-24',1);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (2,'9:00:00','11:30:00','2021-08-24',1);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (2,'12:00:00','2:30:00','2021-08-24',1);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (1,'9:00:00','11:30:00','2021-08-24',2);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (1,'12:00:00','2:30:00','2021-08-24',2);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (2,'9:00:00','11:30:00','2021-08-24',2);
INSERT INTO SCHEDULE (MOVIEID,TIMESTART,TIMEEND,SELECTEDDATE,CINEMAID) VALUES (2,'12:00:00','2:30:00','2021-08-24',2);

INSERT INTO SEAT (SCHEDULEID) VALUES (1);
INSERT INTO SEAT (SCHEDULEID) VALUES (1);
INSERT INTO SEAT (SCHEDULEID) VALUES (1);
INSERT INTO SEAT (SCHEDULEID) VALUES (1);
INSERT INTO SEAT (SCHEDULEID) VALUES (1);

INSERT INTO SEAT (SCHEDULEID) VALUES (2);
INSERT INTO SEAT (SCHEDULEID) VALUES (2);
INSERT INTO SEAT (SCHEDULEID) VALUES (2);
INSERT INTO SEAT (SCHEDULEID) VALUES (2);
INSERT INTO SEAT (SCHEDULEID) VALUES (2);

INSERT INTO USERS (USERNAME,PASSWORD) VALUES ('Bobby','Bobbest');
INSERT INTO USERS (USERNAME,PASSWORD) VALUES ('Larry','Larrest');


INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE) VALUES (1,'1,2,3,2,1',1000);
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE) VALUES (1,'1,2,1',200);
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE) VALUES (2,'3,2,1',300);

INSERT INTO FOOD (PACKAGENAME,PACKAGEDETAILS,PACKAGEPRICE) VALUES ('Package 1','Hotdog and Drink',100);
INSERT INTO FOOD (PACKAGENAME,PACKAGEDETAILS,PACKAGEPRICE) VALUES ('Package 2','Popcorn and Drink',95);
INSERT INTO FOOD (PACKAGENAME,PACKAGEDETAILS,PACKAGEPRICE) VALUES ('Package 3','Nacho and Drink',90);
INSERT INTO FOOD (PACKAGENAME,PACKAGEDETAILS,PACKAGEPRICE) VALUES ('Package 4','Chips and Drink',80);
INSERT INTO FOOD (PACKAGENAME,PACKAGEDETAILS,PACKAGEPRICE) VALUES ('Package 5','Chocolate and Drink',150);






