DELETE FROM orders;

ALTER TABLE orders
	ADD COLUMN
	email VARCHAR(200);

ALTER TABLE orders
	ADD COLUMN
	orderStatus BOOL NOT NULL;

ALTER TABLE orders
	ADD COLUMN
	transactionID varchar(50) NOT NULL;

INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID) VALUES (1,'1,2,3,2,1',1000, 'martier@oocl.com', false, 'QWE123');
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID) VALUES (1,'1,2,1',200, null, false, 'QWE124');
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID) VALUES (2,'3,2,1',300, 'magluar@oocl.com', false, 'QWE125');
