DELETE FROM orders;

ALTER TABLE orders
    ADD scheduleId INT NOT NULL;

ALTER TABLE orders
    ADD FOREIGN KEY (scheduleId) REFERENCES schedule(scheduleId);


INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID,SCHEDULEID) VALUES (1,'1,2,3,2,1',1000, 'martier@oocl.com', false, 'QWE123',1);
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID,SCHEDULEID) VALUES (1,'1,2,1',200, null, false, 'QWE124',2);
INSERT INTO ORDERS (USERID,FOODLIST,TOTALPRICE,EMAIL,ORDERSTATUS,TRANSACTIONID,SCHEDULEID) VALUES (2,'3,2,1',300, 'magluar@oocl.com', false, 'QWE125',2);
